name: ci-dev

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: ${{ matrix.architecture }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ matrix.architecture }}
          push: true
          tags: jocxfin/pwgen-dev:${{ matrix.architecture }}
  
  merge:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create and push multi-architecture manifest
        uses: docker/bake-action@v6
        with:
          targets: image-manifest
          push: true
          files: |
            ./docker-bake.hcl
          set: |
            *.tags=jocxfin/pwgen-dev:latest
